---
- name: Obtener la configuración de red
  hosts: all
  
  tasks:
    - name: Ejecutar ifconfig
      command: ip addr
      register: ipaddr_output

    - name: Mostrar la salida de ifconfig
      debug:
        msg: "Resultado {{ ipaddr_output.content }}"
